apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-service-account
  namespace: fiapx-worker
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::239409137076:role/fiapx-worker-app-role # Substitua pelo ARN do seu IAM Role na AWS
